all:
	mkdir -p ./build
	$(CXX) -o ./build/—urrency—onvertor ./library/src/CurrencyConvert.cpp ./sample/CurrencyConvert.cpp ./library/src/—urrenÒy—onvertApplication.cpp -I./

test: all
	./build/CurrencyConvertor